package br.com.senac.atividade5piuc05.gui;

import br.com.senac.atividade5piuc05.users.Usuario;
import br.com.senac.atividade5piuc05.users.Usuario.ComboItem;
import br.com.senac.atividade5piuc05.users.UsuarioDAO;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme denes
 */
public class Usuarios extends javax.swing.JFrame {
    // os outros atributos da classe Usuario
    private JComboBox<ComboItem> comTipoUsuario;


    private UsuarioDAO usuariosDAO;   // declarando a variável

    private int id_permissao;//criando um método global para poder permissao liberar acesso crud

    public Usuarios() {
        initComponents();
        // inicializando o combo box
        comTipoUsuario = new JComboBox<>();

       




        usuariosDAO = new UsuarioDAO();//inicializando a variável

        List<Usuario> usuario = buscaDados();
        preencheTabela(usuario);

        ImageIcon pesquisar = new ImageIcon(getClass().getResource("/META-INF/search-lens.png"));
        Image image = pesquisar.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        pesquisar = new ImageIcon(image);
        btnPesUsuario.setIcon(pesquisar);

        ImageIcon cadastrar = new ImageIcon(getClass().getResource("/META-INF/9224390_add_plus_new_create_control_icon.png"));
        Image image1 = cadastrar.getImage().getScaledInstance(48, 48, Image.SCALE_SMOOTH);
        cadastrar = new ImageIcon(image1);
        btnCadastrar.setIcon(cadastrar);

        ImageIcon editar = new ImageIcon(getClass().getResource("/META-INF/9224363_edit_pencil_write_pen_tool_icon.png"));
        Image image2 = editar.getImage().getScaledInstance(48, 48, Image.SCALE_SMOOTH);
        editar = new ImageIcon(image2);
        btnEditar.setIcon(editar);

        ImageIcon remover = new ImageIcon(getClass().getResource("/META-INF/table_delete_icon.png"));
        Image image3 = remover.getImage().getScaledInstance(48, 48, Image.SCALE_SMOOTH);
        remover = new ImageIcon(image3);
        btnRemover.setIcon(remover);

        ImageIcon carregarDados = new ImageIcon(getClass().getResource("/META-INF/upload_database_icon.png"));
        Image image4 = carregarDados.getImage().getScaledInstance(48, 48, Image.SCALE_SMOOTH);
        carregarDados = new ImageIcon(image4);
        btnCarregarDados.setIcon(carregarDados); // Define o novo ImageIcon no botão

        ImageIcon logo = new ImageIcon(getClass().getResource("/META-INF/logo_mobel.gif"));
        Image image5 = logo.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
        logo = new ImageIcon(image5);
        txtLogoMobel1.setIcon(logo);

  


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNomeUsuario = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        comTipoUsuario = new javax.swing.JComboBox<>();
        txtPesquisarUsuario = new javax.swing.JTextField();
        btnPesUsuario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCarregarDados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtIdPermissoes = new javax.swing.JTextField();
        txtLogoMobel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadCli = new javax.swing.JMenuItem();
        menCadPro = new javax.swing.JMenuItem();
        menCadCat = new javax.swing.JMenuItem();
        menCadUsu = new javax.swing.JMenuItem();
        menCadOrc = new javax.swing.JMenuItem();
        menCadOs = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRelSer = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();
        menAjuSob = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menOpcSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mobel Loc - Usuários");

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 440));

        desktop.setBackground(new java.awt.Color(217, 197, 216));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Login");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tipo");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        comTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente Geral", "Gerente ", "Operador", " " }));
        comTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTipoUsuarioActionPerformed(evt);
            }
        });

        txtPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarUsuarioActionPerformed(evt);
            }
        });

        btnPesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesUsuarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("pesquisar");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCarregarDados.setText("Carregar Dados");
        btnCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarDadosActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(217, 197, 216));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários"));

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Login", "Senha", "Tipo", "Id Permissões"
            }
        ));
        jScrollPane1.setViewportView(tblUsuario);

        jLabel7.setText("Id Permissões");

        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtNomeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(comTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtPesquisarUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(btnPesUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(btnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(btnRemover, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(btnCarregarDados, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtIdPermissoes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(61, 61, 61)
                        .addComponent(btnEditar)
                        .addGap(67, 67, 67)
                        .addComponent(btnRemover)
                        .addGap(55, 55, 55)
                        .addComponent(btnCarregarDados)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(txtPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(btnCarregarDados))
                .addGap(55, 55, 55))
        );

        txtLogoMobel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icons/logo_mobel.gif"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblData.setText("Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(desktop)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogoMobel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblUsuario)
                .addGap(31, 31, 31)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(txtLogoMobel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        menCad.setText("Cadastro");

        menCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadCli.setText("Cliente");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        menCad.add(menCadCli);

        menCadPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadPro.setText("Produtos");
        menCadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadProActionPerformed(evt);
            }
        });
        menCad.add(menCadPro);

        menCadCat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadCat.setText("Categorias");
        menCadCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCatActionPerformed(evt);
            }
        });
        menCad.add(menCadCat);

        menCadUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadUsu.setText("Usuários");
        menCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuActionPerformed(evt);
            }
        });
        menCad.add(menCadUsu);

        menCadOrc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadOrc.setText("Orçamentos");
        menCadOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadOrcActionPerformed(evt);
            }
        });
        menCad.add(menCadOrc);

        menCadOs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadOs.setText("Ordem Serviços");
        menCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadOsActionPerformed(evt);
            }
        });
        menCad.add(menCadOs);

        menu.add(menCad);

        menRel.setText("Relatório");

        menRelSer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menRelSer.setText("Ordem Serviço");
        menRel.add(menRelSer);

        menu.add(menRel);

        menAju.setText("Ajuda");

        menAjuSob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menAjuSob.setText("Sobre");
        menAju.add(menAjuSob);

        menu.add(menAju);

        menOpc.setText("Opções");

        menOpcSai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menOpcSai.setText("Sair");
        menOpc.add(menOpcSai);

        menu.add(menOpc);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadCliActionPerformed

    private void menCadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadProActionPerformed

    private void menCadCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadCatActionPerformed

    private void menCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadUsuActionPerformed

    private void menCadOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadOrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadOrcActionPerformed

    private void menCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadOsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menCadOsActionPerformed

    private void btnPesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesUsuarioActionPerformed
        try {
            List<Usuario> usuario = buscaDados();
            preencheTabela(usuario);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnPesUsuarioActionPerformed

    private void txtPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarUsuarioActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Usuario novoUsuario = new Usuario();

        try {
            //para a descrição capturamos direto o valor do campo de texto
            novoUsuario.setNome(txtNomeUsuario.getText());
            novoUsuario.setLogin(txtLogin.getText());
            novoUsuario.setSenha(txtSenha.getSelectedText());
            novoUsuario.setTipo((String) comTipoUsuario.getSelectedItem());
            novoUsuario.setId_permissoes(Integer.parseInt(txtIdPermissoes.getText()));

            UsuarioDAO usuarioDAO = new UsuarioDAO();

            usuarioDAO.cadastrar(novoUsuario);

            //fechando a tela após o cadastros
            LimparCampos();
            this.dispose();

            Usuarios usuarios = new Usuarios();
            usuarios.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Ocorreu uma falha :\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        try {
            if (tblUsuario.getSelectedRow() >= 0) {
                //há linha selecionada na tabela, obter o id
                String id = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0);
                //obtendo o objeto Cliente do id selecionado...

                String Nome_Cliente = txtCliente.getText();
                String Cpf = txtCpf.getText();
                String Cnpj = txtCnpj.getText();
                String Endereco = txtEndereco.getText();
                String e_mail = txtEmail.getText();
                String Fone = txtFone.getText();
                //AQUI ESTA SENDO ENVIADO ATRAVES DO GET E SET DA CLASSE CLIENTES, PARA O BANCO DE DADOS AS ALTERACOES, DAS VARIAVEIS, QUE ESTAO DENTRO DOS PARENTESES
                Clientes c = clientesDAO.obter(Integer.parseInt(id));
                c.setNome_cliente(txtCliente.getText());
                c.setCpf(txtCpf.getText());
                c.setCnpj(txtCnpj.getText());
                c.setEndereço(txtEndereco.getText());

                String dataNascimentoTexto = txtDataNascimento.getText();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/y");
                LocalDate dataNascimento = LocalDate.parse(dataNascimentoTexto, formatter);
                c.setData_nascimento(dataNascimento);

                c.setE_mail(txtEmail.getText());
                c.setFone(txtFone.getText());

                //AGORA PRECISAMOS DA CLASSE DOS CRUDS AONDE TEMOS O ATUALIZAR PARA FAZER A JUNCAO COM O BD
                ClientesDAO clientesDAO = new ClientesDAO();

                clientesDAO.atualizar(c);
                preencherFormulario(c);

                System.out.println("Método preencherFormulario chamado");

                LimparCampos();
                dispose();
                ListagemClientes listagem = new ListagemClientes();
                listagem.setVisible(true);

                //Fecha a janela atual e abre a janela de listagem de clientes
            } else {
                System.out.println("Nenhuma linha selecionada na tabela");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falhaaqui:\n" + e.getMessage());
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            if (tblUsuario.getSelectedRow() >= 0) { //verifica se há algo selecionado na tabela
                //obtém o valor da coluna id da linha selecionada
                String id = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0);
                //janela de confirmação
                int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o registro " + id + "?");
                if (resposta == 0)//0- yes, 1- no, 2- cancel
                {
                    //realizando a exclusão
                    ClientesDAO despesaDao = new ClientesDAO();
                    despesaDao.excluir(Integer.parseInt(id));
                    JOptionPane.showMessageDialog(this, "Registro excluído com sucesso");
                    //refazendo a pesquisa para atualizar a tabela na tela
                    btnPesClientesActionPerformed(evt);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarDadosActionPerformed
        CarregarCampos();
    }//GEN-LAST:event_btnCarregarDadosActionPerformed

    private void comTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTipoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCarregarDados;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPesUsuario;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> comTipoUsuario;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenuItem menAjuSob;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadCat;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenuItem menCadOrc;
    private javax.swing.JMenuItem menCadOs;
    private javax.swing.JMenuItem menCadPro;
    private javax.swing.JMenuItem menCadUsu;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenuItem menOpcSai;
    private javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelSer;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPermissoes;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtLogoMobel1;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtPesquisarUsuario;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private List<Usuario> buscaDados() {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        List<Usuario> usuario = usuariosDAO.listar(txtPesquisarUsuario.getText());
        return usuario;
    }

    public void preencheTabela(List<Usuario> usuario) {
        String columns[] = {"Id", "Nome", "Login", "Senha", "Tipo", "id_permissoes"};
        String dados[][] = new String[usuario.size()][columns.length];

        int i = 0;
        for (Usuario u : usuario) {
            dados[i] = new String[]{
                String.valueOf(u.getId()),
                u.getNome(),
                u.getLogin(),
                u.getSenha(),
                u.getTipo(),
                String.valueOf(u.getId_permissoes())
            };

            i++;
        }

        DefaultTableModel model = new DefaultTableModel(dados, columns);
        tblUsuario.setModel(model);
    }

    public void preencherFormulario(Usuario usuario) {
        txtNomeUsuario.setText(usuario.getNome());
        txtLogin.setText(usuario.getLogin());
        txtSenha.setText(usuario.getSenha());
        txtIdPermissoes.setText(String.valueOf(usuario.getId_permissoes()));
// Selecionando o item do combo box pelo valor de id_permissoes
        for (int i = 0; i < comTipoUsuario.getItemCount(); i++) {
            Usuario.ComboItem item = (Usuario.ComboItem) comTipoUsuario.getItemAt(i);
            if (item.getId_permissoes().equals(usuario.getId_permissoes())) {
                comTipoUsuario.setSelectedIndex(i);
                break;
            }
        }
    }

    public void validaPermissao(int id) {
        this.id_permissao = id;
        if (id_permissao == 3) {
            btnCadastrar.setVisible(false);
            btnEditar.setVisible(false);
            btnRemover.setVisible(false);
        } else if (id_permissao == 2) {
            btnEditar.setVisible(false);
            btnRemover.setVisible(false);
        }
    }

    private void LimparCampos() {
        txtNomeUsuario.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        comTipoUsuario.setSelectedItem(null);
        txtIdPermissoes.setText("");
        txtNomeUsuario.requestFocus();
    }

}
